### ISSUE TITLE
Search Bar + Result page

### ISSUE THREAD

**Issue by ZakMos** [hsh4you/hsh4you.github.io#18]
<script async src="https://cse.google.com/cse.js?cx=011360283836416082212:c30etgws4qs" ></script>

**Comment by danieldreke** [comment]
Information for non-profits
https://support.google.com/customsearch/answer/4542102

**Comment by danieldreke** [comment]
Custom Search Engine
https://cse.google.com

**Comment by danieldreke** [comment]
Styling
- https://www.webslake.com/article/customizing-design-of-google-custom-search-box-using-css/
- https://www.labnol.org/internet/google-custom-search-css/28360/
